default:
    site:
        review_period: '6 months'
        review_release_date: 2016-01-01
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation
            -
                space_path: admindoc
                space_name: Nuxeo Installation and Administration
        versions:
            -
                label: FT
            -
                is_current_version: true
                label: LTS 2015
                url_path: '710'
            -
                label: '6.0'
                url_path: '60'
            -
                label: '5.8'
                url_path: '58'

development:
    isDev: true
