default:
  site:
    review_period: '13 months'
    spaces:
      - space_path: nxdoc
        space_name: Developer Documentation Center
      - space_path: userdoc
        space_name: Nuxeo Platform User Documentation
    branch: '910'
    dev_browser_path: nxdoc/910
    repo_id: platform
    versions:
      - label: LTS 2023
      - label: LTS 2021
        url_path: '2021'
      - label: LTS 2019
        url_path: '1010'
      - label: LTS 2017
        is_current_version: true
        url_path: '910'
      - label: LTS 2016
        url_path: '810'
development:
  isDev: true
