default:
  site:
    review_period: '18 months'
    spaces:
      - space_path: nxdoc
        space_name: Developer Documentation Center
      - space_path: userdoc
        space_name: Nuxeo Platform User Documentation
    branch: '2023'
    dev_browser_path: nxdoc
    repo_id: platform
    versions:
      - label: LTS 2025
      - label: LTS 2023
        is_current_version: true
        url_path: '2023'
      - label: LTS 2021
        url_path: '2021'
      - label: LTS 2019
        url_path: '1010'
      - label: LTS 2017
        url_path: '910'
      - label: LTS 2016
        url_path: '810'
development:
  isDev: true
