default:
  site:
    review_period: '18 months'
    spaces:
      - space_path: nxdoc
        space_name: Developer Documentation Center
      - space_path: userdoc
        space_name: Nuxeo Platform User Documentation
    branch: 1010
    dev_browser_path: nxdoc
    versions:
      - label: FT
      - label: LTS 2019
        url_path: '1010'
        is_current_version: true
      - label: LTS 2017
        url_path: '910'
      - label: LTS 2016
        url_path: '810'
      - label: LTS 2015
        url_path: '710'
      - label: '6.0'
        url_path: '60'
development:
  isDev: true
